name: Generate Snake

on:
  schedule: # execute after every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Nullo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Harpia-Vieillot
          gif_out_path: dist/Harpia-Vieillot.gif
          svg_out_path: dist/Harpia-Vieillot.svg
      
      - run: git status

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: vin-output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
